[package]
name = "parser"
version = "0.1.0"
authors = ["Matthias Farnbauer-Schmidt <matthias.farnbauer-schmidt@fau.de>"]
edition = "2018"

[dependencies]
pest = "2.1.2"
pest_derive = "2.1.0"
clap = "2.33.0"
anyhow = "1.0.32"

[dev-dependencies]
test-case = "1.0.0"
